# Generated by Django 5.1.7 on 2025-07-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_english', models.CharField(max_length=30)),
                ('name_persian', models.CharField(blank=True, max_length=30)),
                ('score', models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('user_tips', models.TextField(blank=True)),
                ('sets', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
