# Generated by Django 5.1.7 on 2025-07-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_workout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='how_to_do',
            field=models.TextField(blank=True),
        ),
    ]
