# Generated by Django 5.1.7 on 2025-07-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_workout_how_to_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='last_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
